import About from "@/src/components/about/AboutContent.vue";
import CTFWriteupTemplate from "@/src/components/project/CTFWriteupTemplate.vue";
import NormalArticle from "@/src/components/project/NormalArticle.vue";

export const componentsMap: { [key: string]: Component } = {
  "About Me": About,
  "CTF Writeup": CTFWriteupTemplate,
  Web: CTFWriteupTemplate,
  Crypto: CTFWriteupTemplate,
  Misc: CTFWriteupTemplate,
  "Ave Mujica": CTFWriteupTemplate,
  "Be IDol": CTFWriteupTemplate,
  Mango: CTFWriteupTemplate,
  "2DES": CTFWriteupTemplate,
  "Mystery Presentation": CTFWriteupTemplate,
  "Packet Detective": CTFWriteupTemplate,
  "Math Test": CTFWriteupTemplate,
  "3-Cipher": CTFWriteupTemplate,
  "addition-quiz": CTFWriteupTemplate,
  php7cmp4re: CTFWriteupTemplate,
  ROT128: CTFWriteupTemplate,
  "64se64": CTFWriteupTemplate,
  "Snowing!": CTFWriteupTemplate,
  lolololologfile: CTFWriteupTemplate,
  d: CTFWriteupTemplate,
  "xss-1": CTFWriteupTemplate,
  "xss-2": CTFWriteupTemplate,
  "csrf-1": CTFWriteupTemplate,
  "csrf-2": CTFWriteupTemplate,
  simple_sqli: CTFWriteupTemplate,
  "image-storage": CTFWriteupTemplate,
  "Mango (Dreamhack)": CTFWriteupTemplate,
  "session-basic": CTFWriteupTemplate,
  "Summer Fan": CTFWriteupTemplate,
  "Secure Secret": CTFWriteupTemplate,
  "rev-basic-1": CTFWriteupTemplate,
  "[wargame.kr] strcmp": CTFWriteupTemplate,
  "Small Counter": CTFWriteupTemplate,
  Summary: NormalArticle,
  "Basic Switch and End Device Configuration": NormalArticle,
  "Protocols and Models": NormalArticle,
  "L1 - L3 test": NormalArticle,
  "QR Secrets": CTFWriteupTemplate,
  "HTTP Carrier Pigeons": CTFWriteupTemplate,
  "Physical Layer": NormalArticle,
  "EVEN RSA CAN BE BROKEN???": CTFWriteupTemplate,
  "Guess My Cheese (Part 1)": CTFWriteupTemplate,
  "Guess My Cheese (Part 2)": CTFWriteupTemplate,
  hashcrack: CTFWriteupTemplate,
  "Bitlocker-1": CTFWriteupTemplate,
  "Bitlocker-2": CTFWriteupTemplate,
  "Event-Viewing": CTFWriteupTemplate,
  "Ph4nt0m 1ntrud3r": CTFWriteupTemplate,
  RED: CTFWriteupTemplate,
  "Cookie Monster Secret Recipe": CTFWriteupTemplate,
  "head-dump": CTFWriteupTemplate,
  SSTI1: CTFWriteupTemplate,
  "picoCTF 2025 Summary": NormalArticle,
  "proxy-1": CTFWriteupTemplate,
  "L4 - L7 test": NormalArticle,
  "Crypto L2": NormalArticle,
  "Crypto L1": NormalArticle,
  "Crypto L0": NormalArticle,
  "Crypto L3": NormalArticle,
  "L8 - L10 test": NormalArticle,
  "L11 - L13 test": NormalArticle,
  simple_sqli_chatgpt: CTFWriteupTemplate,
  "Audio Steganography": CTFWriteupTemplate,
  "Crypto L3-lm": NormalArticle,
  "Easy Assembly": CTFWriteupTemplate,
};
