import About from "@/src/components/about/AboutContent.vue";
import CTFWriteupTemplate from "@/src/components/project/CTFWriteupTemplate.vue";
import NormalArticle from "@/src/components/project/NormalArticle.vue";

export const componentsMap: { [key: string]: Component } = {
  "About Me": About,
  "CTF Writeup": CTFWriteupTemplate,
  Web: CTFWriteupTemplate,
  Crypto: CTFWriteupTemplate,
  Misc: CTFWriteupTemplate,
  "Ave Mujica": CTFWriteupTemplate,
  "Be IDol": CTFWriteupTemplate,
  Mango: CTFWriteupTemplate,
  "2DES": CTFWriteupTemplate,
  "Mystery Presentation": CTFWriteupTemplate,
  "Packet Detective": CTFWriteupTemplate,
  "Math Test": CTFWriteupTemplate,
  "3-Cipher": CTFWriteupTemplate,
  "addition-quiz": CTFWriteupTemplate,
  php7cmp4re: CTFWriteupTemplate,
  ROT128: CTFWriteupTemplate,
  "64se64": CTFWriteupTemplate,
  "Snowing!": CTFWriteupTemplate,
  lolololologfile: CTFWriteupTemplate,
  d: CTFWriteupTemplate,
  "xss-1": CTFWriteupTemplate,
  "xss-2": CTFWriteupTemplate,
  "csrf-1": CTFWriteupTemplate,
  "csrf-2": CTFWriteupTemplate,
  simple_sqli: CTFWriteupTemplate,
  "image-storage": CTFWriteupTemplate,
  "Mango (Dreamhack)": CTFWriteupTemplate,
  "session-basic": CTFWriteupTemplate,
  "Summer Fan": CTFWriteupTemplate,
  "Secure Secret": CTFWriteupTemplate,
  "rev-basic-1": CTFWriteupTemplate,
  "[wargame.kr] strcmp": CTFWriteupTemplate,
  "Small Counter": CTFWriteupTemplate,
  Summary: NormalArticle,
  "Basic Switch and End Device Configuration": NormalArticle,
  "Protocols and Models": NormalArticle,
  "L1 - L3 test": NormalArticle,
};
