name: Delete Merged Branch

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete the branch after merge
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref != 'main'
        run: |
          git fetch origin +refs/heads/*:refs/heads/*
          git branch -d "${GITHUB_HEAD_REF}" || echo "Failed to delete branch locally"
          git push origin --delete "${GITHUB_HEAD_REF}" || echo "Failed to delete branch remotely"
